// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Project struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}

type Request struct {
	ID        int64
	ProjectID int64
	Name      string
	Curl      string
	Method    string
	Url       string
	Headers   sql.NullString
	Body      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type SelectedProject struct {
	ProjectID int64
}
